---
version: "3"

services:
    flask-app:
        build:
            context: ./
            dockerfile: ./Dockerfile
        image: jthet/iss_tracker:1.0
        volumes:
                - ./config.yaml:/config.yaml