---
version: "3"

services:
    flask-app:
        build:
            context: ./
            dockerfile: ./Dockerfile
        image: jthet/iss_tracker:1.0
        ports:
            -   "5000:5000"
        volumes:
            - ./config.yaml:/config.yaml